#ifndef __APP_HANDLER_H_
#define __APP_HANDLER_H_

#include "Platform.h"
#if PL_CONFIG_BOARD_IS_REMOTE
#include <stdint.h>

typedef enum {
	APPHDL_APP_ID_TETRIS,
	APPHDL_APP_ID_SNAKE,
	APPHDL_APP_ID_ROBO,
	APPHDL_APP_ID_NONE,
} APPHDL_AppIDs;

typedef enum {
	APPHDL_EVENT_ENTER_APPLICATION,
	APPHDL_EVENT_BTN_UP,
	APPHDL_EVENT_BTN_DOWN,
	APPHDL_EVENT_BTN_LEFT,
	APPHDL_EVENT_BTN_RIGHT,
	APPHDL_EVENT_BTN_CENTER,
	APPHDL_EVENT_BTN_CENTER_LONG,
	APPHDL_EVENT_BNT_RIGHT_UP,
	APPHDL_EVENT_BNT_RIGHT_UP_LONG,
	APPHDL_EVENT_BTN_RIGHT_DOWN,
	APPHDL_EVENT_EXIT_APPLICATION,
} APPHDL_EventTypes;

bool APPHDL_isInAppMode;

void APPHDL_SetAppID(APPHDL_AppIDs id);

void APPHDL_OnEvent(APPHDL_EventTypes evnt);

void APPHDL_init(void);

#endif // PL_CONFIG_BOARD_IS_REMOTE
#endif //__APP_HANDLER_H_
